### ISSUE TITLE
AttributeError: Can only use .dt accessor with datetimelike values

### ISSUE THREAD

**Issue by alokranjan1234** [Roytsai27/Dual-Attentive-Tree-aware-Embedding#3]
I am getting the error while training on my dataset:-

Traceback (most recent call last):
  File "preprocess_data.py", line 148, in <module>
    train = preprocess(train)
  File "preprocess_data.py", line 62, in preprocess
    df.loc[:, 'SGD.DayofYear'] = df['sgd.date'].dt.dayofyear
  File "/home/alok/anaconda3/envs/DATE/lib/python3.8/site-packages/pandas/core/generic.py", line 5132, in __getattr__       return object.__getattribute__(self, name)
  File "/home/alok/anaconda3/envs/DATE/lib/python3.8/site-packages/pandas/core/accessor.py", line 187, in __get__           accessor_obj = self._accessor(obj)
  File "/home/alok/anaconda3/envs/DATE/lib/python3.8/site-packages/pandas/core/indexes/accessors.py", line 480, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values

**Comment by Seondong** [comment]
Hi @alokranjan1234, would you like to check the format of the variable 'sgd.date'?
I guess this problem will be solved by modifying your data type or data format.
Refer to some [articles](https://www.google.com/search?q=Can+only+use+.dt+accessor+with+datetimelike+values&pws=0&gl=us&gws_rd=cr).

**Comment by alokranjan1234** [comment]
Hi @Seondong, thanks for the reply. The dates were in the correct format but still, we were getting the error. We were able to resolve it using pandas to_datetime method to transform to datetime format instead of apply method. We are able to train the model on our dataset but the model is not performing well. We are getting low precision and recall scores. Can you suggest some strategies for feature engineering and parameter tuning? we are using a dataset of 1 million sample size.

**Comment by Seondong** [comment]
Hi @alokranjan1234, the performance will surely depend on feature engineering. So feel free to play with the pipelines.
The easiest way to play with is to add additional features in `preprocess_data.py` or change hyperparameters of the DATE (or XGB) model. 

We reported some hyperparameter analysis results on the [appendix of our paper](https://dl.acm.org/doi/pdf/10.1145/3394486.3403339), the results may slightly different between datasets.

Also, in the model part, we used HS code and Importer ID as additional features, you can modify/add additional variables that are known to be important in your domain.
