### ISSUE TITLE
'std::bad_alloc' error while loading xgboost model

### ISSUE THREAD

**Issue by alokranjan1234** [Roytsai27/Dual-Attentive-Tree-aware-Embedding#4]
I am getting 'std::bad_alloc' error while loading the xgboost model to preprocess data for prediction:-

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

How can I resolve this?

**Comment by Seondong** [comment]
@alokranjan1234 
Can you check your machine has enough memory?
It seems the error occurs when there is not enough memory.

https://stackoverflow.com/questions/29309681/what-stdbad-alloc-am-i-out-of-memory
https://github.com/dmlc/xgboost/issues/1032

**Comment by alokranjan1234** [comment]
@Seondong 
The error was due to a bug in xgboost, even with enough memory it shows the error. Saving the model in binary serialized format resolved the issue.

**Comment by alokranjan1234** [comment]
Also, on a side note if you can share your experiences related to serving the model in production (logging, monitoring, etc) perhaps in a blog or medium article that will help a lot.

**Comment by Seondong** [comment]
@alokranjan1234 
Thanks for your suggestion. We are currently modulizing our code to support end-users to easily test their selection strategy on diverse custom selection scenarios. Stay tuned.

**Comment by alokranjan1234** [comment]
@Seondong 
Let me know if I can be of any help.
