### ISSUE TITLE
Jupyter-notebook ModuleNotFoundError: No module named 'ranger'

### ISSUE THREAD

**Issue by Ichankasep** [Roytsai27/Dual-Attentive-Tree-aware-Embedding#5]
Dear team, I have an issue to load ranger library.

the error return information is ModuleNotFoundError: No module named 'ranger' 

I have try to install the library with this code 

```
import sys  
!{sys.executable} -m pip install --user ranger
```

But the issue is still remain.
Is there any suggestion?
Thank you.

For information.
Jupyter Python 3.7
Pip 20.0.2

**Comment by Seondong** [comment]
Hi @Ichankasep, you can install the Ranger optimizer by following the instruction of their Github repository.
Here is the link: [Link](https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer#installation)
You can also use famous optimizers such as Adam or SGD instead of the Ranger.

**Comment by Ichankasep** [comment]
Ah I see.
Thanks for your information.

Regards.
